package types

// Auto Generated by https://mholt.github.io/json-to-go/
type (
	TmdbSearchMovieResultSet struct {
		Page         int                `json:"page"`
		TotalPages   int                `json:"total_pages"`
		TotalResults int                `json:"total_results"`
		Results      []*TmdbMovieResult `json:"results"`
	}

	TmdbMovieResult struct {
		Adult            bool    `json:"adult"`
		BackdropPath     *string `json:"backdrop_path"`
		GenreIds         []*int  `json:"genre_ids"`
		ID               int     `json:"id"`
		OriginalLanguage string  `json:"original_language"`
		OriginalTitle    string  `json:"original_title"`
		Overview         *string `json:"overview"`
		Popularity       float64 `json:"popularity"`
		PosterPath       *string `json:"poster_path"`
		ReleaseDate      string  `json:"release_date"`
		Title            string  `json:"title"`
		Video            bool    `json:"video"`
		VoteAverage      float64 `json:"vote_average"`
		VoteCount        int     `json:"vote_count"`
	}

	tmdbBelongsToCollection struct {
		ID           int    `json:"id"`
		Name         string `json:"name"`
		PosterPath   string `json:"poster_path"`
		BackdropPath string `json:"backdrop_path"`
	}

	tmdbGenre struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
	}

	tmdbProductionCompanies struct {
		ID            int    `json:"id"`
		LogoPath      string `json:"logo_path"`
		Name          string `json:"name"`
		OriginCountry string `json:"origin_country"`
	}

	tmdbProductionCountries struct {
		Iso31661 string `json:"iso_3166_1"`
		Name     string `json:"name"`
	}

	tmdbSpokenLanguages struct {
		EnglishName string `json:"english_name"`
		Iso6391     string `json:"iso_639_1"`
		Name        string `json:"name"`
	}

	TmdbMovieDetail struct {
		Adult               bool                      `json:"adult"`
		BackdropPath        string                    `json:"backdrop_path"`
		BelongsToCollection tmdbBelongsToCollection   `json:"belongs_to_collection"`
		Budget              int                       `json:"budget"`
		Genres              []tmdbGenre               `json:"genres"`
		Homepage            string                    `json:"homepage"`
		ID                  int                       `json:"id"`
		ImdbID              string                    `json:"imdb_id"`
		OriginCountry       []string                  `json:"origin_country"`
		OriginalLanguage    string                    `json:"original_language"`
		OriginalTitle       string                    `json:"original_title"`
		Overview            string                    `json:"overview"`
		Popularity          float64                   `json:"popularity"`
		PosterPath          string                    `json:"poster_path"`
		ProductionCompanies []tmdbProductionCompanies `json:"production_companies"`
		ProductionCountries []tmdbProductionCountries `json:"production_countries"`
		ReleaseDate         string                    `json:"release_date"`
		Revenue             int                       `json:"revenue"`
		Runtime             int                       `json:"runtime"`
		SpokenLanguages     []tmdbSpokenLanguages     `json:"spoken_languages"`
		Status              string                    `json:"status"`
		Tagline             string                    `json:"tagline"`
		Title               string                    `json:"title"`
		Video               bool                      `json:"video"`
		VoteAverage         float32                   `json:"vote_average"`
		VoteCount           int32                     `json:"vote_count"`
	}
)
