@endpoint = http://localhost:8000/v1
@token = xyz

// --- 異常系 --- //

PUT {{endpoint}}/reviews/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rating": null,
    "comment": null
}

###

PUT {{endpoint}}/reviews/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rating": 0.0,
    "comment": null
}

###

PUT {{endpoint}}/reviews/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rating": 5.1,
    "comment": null
}

###

PUT {{endpoint}}/reviews/404
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rating": 3.1,
    "comment": null
}

###


// --- 正常系 --- //

PUT {{endpoint}}/reviews/1/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "rating": 3.1,
    "comment": null
}
