DROP DATABASE IF EXISTS db4dev;
DROP DATABASE IF EXISTS db4test;

CREATE DATABASE db4dev
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE db4test
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON db4test.* TO 'user'@'%';
FLUSH PRIVILEGES;
