@endpoint = http://localhost:8000/v1/search/movies
@token = xyz


GET {{endpoint}}
?title=ターミネーター
Authorization: Bearer {{token}}


###

GET {{endpoint}}
?title=君
&limit=10
&offset=7
Authorization: Bearer {{token}}
