@endpoint = http://localhost:8000/v1

@movieTerminator = 218
@movieTerminator2 = 280
@movieNotFound = 404

GET {{endpoint}}/movies/{{movieTerminator}}

###

GET {{endpoint}}/movies/{{movieTerminator2}}

###

GET {{endpoint}}/movies/{{movieNotFound}}
