@endpoint = http://localhost:8000/v0

@movieTerminator = 218
@movieTerminator2 = 280
@movieNotFound = 404

POST {{endpoint}}/movies/{{movieTerminator}}/impression
Content-Type: application/json

{
    "watchDate": "2016-12-25",
    "mediaCode": "Prime Video"
}

###

POST {{endpoint}}/movies/{{movieTerminator2}}/impression
Content-Type: application/json

{
    "watchDate": "2016-12-25",
    "mediaCode": "Netflix",
    "rating": 1.59,
    "note": "アストロノート"
}

###

POST {{endpoint}}/movies/{{movieNotFound}}/impression
Content-Type: application/json

{
    "watchDate": "2016-12-25",
    "mediaCode": "Prime Video"
}
