@endpoint = http://localhost:8000/v0

@movieTerminator = 218
@movieTerminator2 = 280
@movieNotFound = 404

@recordA = 1

PUT {{endpoint}}/movies/{{movieTerminator}}/records/{{recordA}}
Content-Type: application/json

{
    "mediaCode": "cinema",
    "date": "2016-12-25"
}
