name: Backend Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ARCH: x64

jobs:
  test-echo:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          cp ./api-echo/.example.env ./api-echo/.env

      - name: Build Image & Run Container
        run: |
          docker compose -f compose.shared.yml -f compose.echo.yml build
          docker compose -f compose.shared.yml -f compose.echo.yml up -d db
          sleep 30
          docker compose -f compose.shared.yml -f compose.echo.yml logs db
          docker compose -f compose.shared.yml -f compose.echo.yml up -d api_echo
          docker compose -f compose.shared.yml -f compose.echo.yml ps

      - name: Run Tests in Container
        run: |
          docker compose -f compose.shared.yml -f compose.echo.yml exec api_echo gotest -v ./... -cover

  test-hono:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: cp ./api-hono/.example.env ./api-hono/.env

      - name: Build & Test
        run: |
          docker compose -f compose.shared.yml -f compose.hono.yml build
          docker compose -f compose.shared.yml -f compose.hono.yml up -d db
          sleep 30
          docker compose -f compose.shared.yml -f compose.hono.yml up -d api_hono
          docker compose -f compose.shared.yml -f compose.hono.yml exec api_hono bun test
