name: Go Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ARCH: x64

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          cp ./api-echo/.example.env ./api-echo/.env

      - name: Build Image & Run Container
        run: |
          docker compose -f compose.shared.yml -f compose.echo.yml build
          docker compose -f compose.shared.yml -f compose.echo.yml up -d db
          sleep 30
          docker compose -f compose.shared.yml -f compose.echo.yml logs db
          docker compose -f compose.shared.yml -f compose.echo.yml up -d api
          docker compose -f compose.shared.yml -f compose.echo.yml ps

      - name: Run Tests in Container
        run: |
          docker compose -f compose.shared.yml -f compose.echo.yml exec api gotest -v ./... -cover
